# ===============================================
# AUTHELIA AUTHENTICATION & AUTHORIZATION STACK
# ===============================================
# 
# Enterprise-grade authentication solution with:
# - Multi-factor authentication (TOTP, WebAuthn, Duo)
# - Single Sign-On (SSO) integration
# - Role-based access control (RBAC)
# - Redis session storage for high availability
# - Advanced security policies and rate limiting
# ===============================================

services:
  # Authentication Server - Authelia
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    environment:
      - TZ=${TZ}
      - AUTHELIA_LOG_LEVEL=info
    volumes:
      - ${ROOT_CONFIG}/authelia:/config
    ports:
      - 9091:9091
    restart: unless-stopped
    networks:
      - auth_network
      - media_network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.75

  # Session Storage - Redis
  redis:
    image: redis:7-alpine
    container_name: authelia-redis
    volumes:
      - ${ROOT_CONFIG}/authelia/redis:/data
    restart: unless-stopped
    networks:
      - auth_network
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.25

networks:
  auth_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
  media_network:
    external: true
    name: homelab_media_network